[project]
name = "tgfeed"
version = "0.2.0"
description = "Create feeds in Telegram easily"
authors = [
    {name = "Nikolai", email = "magnickolas@gmail.com"},
]
requires-python = ">=3.14"

dependencies = [
    "Telethon~=1.44.0",
    "appdirs<2.0.0,>=1.4.4",
    "loguru<0.8.0,>=0.7.3",
    "jsonpickle<5.0.0,>=4.1.1",
]

[dependency-groups]
dev = [
    "mypy<2.0.0,>=1.17.1",
    "pre-commit<5.0.0,>=4.2.0",
    "removestar<2.0,>=1.5.2",
    "ruff<1.0.0,>=0.16.3",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "I"]
ignore = ["E203"]

[tool.ruff.lint.mccabe]
max-complexity = 25
